CREATE TABLE TARIFFS (
	TARIFF_ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(200) NOT NULL,
	MONTHLY_FEE NUMBER (10,2),
	DATA_LIMIT NUMBER,
	MINUTE_LIMIT NUMBER,
	SMS_LIMIT NUMBER
);

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(200),
	CITY VARCHAR2(200),
	SIGNUP_DATE DATE,
	TARIFF_ID NUMBER,
	CONSTRAINT tariffs_foreignkey FOREIGN KEY (TARIFF_ID)
	REFERENCES TARIFFS(TARIFF_ID)
);

CREATE TABLE MONTHLY_STATS (
	ID NUMBER PRIMARY KEY,
	CUSTOMER_ID NUMBER,
	CONSTRAINT customers_foreignkey FOREIGN KEY (CUSTOMER_ID)
	REFERENCES CUSTOMERS(CUSTOMER_ID),
	DATA_USAGE NUMBER(10,2),
	MINUTE_USAGE NUMBER,
	SMS_USAGE NUMBER,
	PAYMENT_STATUS VARCHAR2(50)
);